ALTER TABLE votes
    DROP CONSTRAINT FK_VOTES_ON_USER;

ALTER TABLE votes
    DROP CONSTRAINT FK_VOTES_ON_POLL;

ALTER TABLE votes
    DROP CONSTRAINT FK_VOTES_ON_OPTION;

ALTER TABLE votes
    DROP CONSTRAINT uc_9e7e8b466a4d440e9cf208851;

DROP TABLE votes;