ALTER TABLE votes
    DROP CONSTRAINT IF EXISTS FK_VOTES_ON_USER;

ALTER TABLE votes
    DROP CONSTRAINT IF EXISTS FK_VOTES_ON_POLL;

ALTER TABLE votes
    DROP CONSTRAINT IF EXISTS FK_VOTES_ON_OPTION;

ALTER TABLE votes
    DROP CONSTRAINT IF EXISTS uc_9e7e8b466a4d440e9cf208851;

DROP TABLE votes;